export default {
  direction: ["inherit", "ltr", "rtl"],
  flexDirection: ["row", "row-reverse", "column", "column-reverse"],
  flexWrap: ["wrap", "no-wrap", "wrap-reverse"],
  justifyContent: [
    "flex-start",
    "center",
    "flex-end",
    "space-between",
    "space-around",
    "space-evenly",
  ],
  alignItems: [
    "flex-start",
    "flex-end",
    "stretch",
    "center",
    "auto",
    "space-between",
    "space-around",
    "baseline",
  ],
  alignSelf: [
    "auto",
    "flex-start",
    "flex-end",
    "stretch",
    "center",
    "auto",
    "space-between",
    "space-around",
    "baseline",
  ],
  alignContent: [
    "auto",
    "flex-start",
    "flex-end",
    "stretch",
    "center",
    "auto",
    "space-between",
    "space-around",
    "baseline",
  ],
};
